### ISSUE TITLE
pre-launch checklist

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/codefordenver.org#80]
- [x] remove featured projects menu and footer componets (moved to post launch board)

- [x] add external links to sponsors

- [x] add a basic 404 page (deferred)
